spring:
  application:
    name: SCS-demo-persoon-sender

  cloud.stream:
    bindings:
      wse_events:
        destination: wse.events
        contentType: application/json
        producer:
          partitionKeyExpression: payload.correlationId
          partitionCount: 1
    rabbit.bindings:
      wse_events:
        producer:
          routingKeyExpression: '''persoon'''
          autoBindDlq: true